<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // A
            ['name' => 'Afghanistan', 'code' => 'AF', 'flag' => '🇦🇫', 'phone_code' => '+93', 'phone_template' => '## ### ####', 'timezone' => 'Asia/Kabul', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Albania', 'code' => 'AL', 'flag' => '🇦🇱', 'phone_code' => '+355', 'phone_template' => '## ### ####', 'timezone' => 'Europe/Tirane', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Algeria', 'code' => 'DZ', 'flag' => '🇩🇿', 'phone_code' => '+213', 'phone_template' => '## ## ## ## ##', 'timezone' => 'Africa/Algiers', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Andorra', 'code' => 'AD', 'flag' => '🇦🇩', 'phone_code' => '+376', 'phone_template' => '### ###', 'timezone' => 'Europe/Andorra', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Angola', 'code' => 'AO', 'flag' => '🇦🇴', 'phone_code' => '+244', 'phone_template' => '### ### ###', 'timezone' => 'Africa/Luanda', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'flag' => '🇦🇬', 'phone_code' => '+1268', 'phone_template' => '###-####', 'timezone' => 'America/Antigua', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Argentina', 'code' => 'AR', 'flag' => '🇦🇷', 'phone_code' => '+54', 'phone_template' => '### ### ####', 'timezone' => 'America/Argentina/Buenos_Aires', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Armenia', 'code' => 'AM', 'flag' => '🇦🇲', 'phone_code' => '+374', 'phone_template' => '## ######', 'timezone' => 'Asia/Yerevan', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Australia', 'code' => 'AU', 'flag' => '🇦🇺', 'phone_code' => '+61', 'phone_template' => '#### ### ###', 'timezone' => 'Australia/Sydney', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Austria', 'code' => 'AT', 'flag' => '🇦🇹', 'phone_code' => '+43', 'phone_template' => '### ### ####', 'timezone' => 'Europe/Vienna', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'flag' => '🇦🇿', 'phone_code' => '+994', 'phone_template' => '## ### ## ##', 'timezone' => 'Asia/Baku', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // B
            ['name' => 'Bahamas', 'code' => 'BS', 'flag' => '🇧🇸', 'phone_code' => '+1242', 'phone_template' => '###-####', 'timezone' => 'America/Nassau', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Bahrain', 'code' => 'BH', 'flag' => '🇧🇭', 'phone_code' => '+973', 'phone_template' => '#### ####', 'timezone' => 'Asia/Bahrain', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Bangladesh', 'code' => 'BD', 'flag' => '🇧🇩', 'phone_code' => '+880', 'phone_template' => '####-######', 'timezone' => 'Asia/Dhaka', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Barbados', 'code' => 'BB', 'flag' => '🇧🇧', 'phone_code' => '+1246', 'phone_template' => '###-####', 'timezone' => 'America/Barbados', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Belarus', 'code' => 'BY', 'flag' => '🇧🇾', 'phone_code' => '+375', 'phone_template' => '## ###-##-##', 'timezone' => 'Europe/Minsk', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Belgium', 'code' => 'BE', 'flag' => '🇧🇪', 'phone_code' => '+32', 'phone_template' => '### ## ## ##', 'timezone' => 'Europe/Brussels', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Belize', 'code' => 'BZ', 'flag' => '🇧🇿', 'phone_code' => '+501', 'phone_template' => '###-####', 'timezone' => 'America/Belize', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Benin', 'code' => 'BJ', 'flag' => '🇧🇯', 'phone_code' => '+229', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Porto-Novo', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Bhutan', 'code' => 'BT', 'flag' => '🇧🇹', 'phone_code' => '+975', 'phone_template' => '## ### ###', 'timezone' => 'Asia/Thimphu', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Bolivia', 'code' => 'BO', 'flag' => '🇧🇴', 'phone_code' => '+591', 'phone_template' => '########', 'timezone' => 'America/La_Paz', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'flag' => '🇧🇦', 'phone_code' => '+387', 'phone_template' => '##-###-###', 'timezone' => 'Europe/Sarajevo', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Botswana', 'code' => 'BW', 'flag' => '🇧🇼', 'phone_code' => '+267', 'phone_template' => '## ### ###', 'timezone' => 'Africa/Gaborone', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Brazil', 'code' => 'BR', 'flag' => '🇧🇷', 'phone_code' => '+55', 'phone_template' => '(##) #####-####', 'timezone' => 'America/Sao_Paulo', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Brunei', 'code' => 'BN', 'flag' => '🇧🇳', 'phone_code' => '+673', 'phone_template' => '### ####', 'timezone' => 'Asia/Brunei', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Bulgaria', 'code' => 'BG', 'flag' => '🇧🇬', 'phone_code' => '+359', 'phone_template' => '## ### ####', 'timezone' => 'Europe/Sofia', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'flag' => '🇧🇫', 'phone_code' => '+226', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Ouagadougou', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Burundi', 'code' => 'BI', 'flag' => '🇧🇮', 'phone_code' => '+257', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Bujumbura', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // C
            ['name' => 'Cabo Verde', 'code' => 'CV', 'flag' => '🇨🇻', 'phone_code' => '+238', 'phone_template' => '### ## ##', 'timezone' => 'Atlantic/Cape_Verde', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Cambodia', 'code' => 'KH', 'flag' => '🇰🇭', 'phone_code' => '+855', 'phone_template' => '## ### ###', 'timezone' => 'Asia/Phnom_Penh', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Cameroon', 'code' => 'CM', 'flag' => '🇨🇲', 'phone_code' => '+237', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Douala', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Canada', 'code' => 'CA', 'flag' => '🇨🇦', 'phone_code' => '+1', 'phone_template' => '(###) ###-####', 'timezone' => 'America/Toronto', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Central African Republic', 'code' => 'CF', 'flag' => '🇨🇫', 'phone_code' => '+236', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Bangui', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Chad', 'code' => 'TD', 'flag' => '🇹🇩', 'phone_code' => '+235', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Ndjamena', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Chile', 'code' => 'CL', 'flag' => '🇨🇱', 'phone_code' => '+56', 'phone_template' => '# #### ####', 'timezone' => 'America/Santiago', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'China', 'code' => 'CN', 'flag' => '🇨🇳', 'phone_code' => '+86', 'phone_template' => '### #### ####', 'timezone' => 'Asia/Shanghai', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Colombia', 'code' => 'CO', 'flag' => '🇨🇴', 'phone_code' => '+57', 'phone_template' => '### ### ####', 'timezone' => 'America/Bogota', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Comoros', 'code' => 'KM', 'flag' => '🇰🇲', 'phone_code' => '+269', 'phone_template' => '## ## ###', 'timezone' => 'Indian/Comoro', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Congo', 'code' => 'CG', 'flag' => '🇨🇬', 'phone_code' => '+242', 'phone_template' => '## ### ####', 'timezone' => 'Africa/Brazzaville', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Congo (Democratic Republic)', 'code' => 'CD', 'flag' => '🇨🇩', 'phone_code' => '+243', 'phone_template' => '### ### ###', 'timezone' => 'Africa/Kinshasa', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Costa Rica', 'code' => 'CR', 'flag' => '🇨🇷', 'phone_code' => '+506', 'phone_template' => '#### ####', 'timezone' => 'America/Costa_Rica', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Croatia', 'code' => 'HR', 'flag' => '🇭🇷', 'phone_code' => '+385', 'phone_template' => '##-###-####', 'timezone' => 'Europe/Zagreb', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Cuba', 'code' => 'CU', 'flag' => '🇨🇺', 'phone_code' => '+53', 'phone_template' => '########', 'timezone' => 'America/Havana', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Cyprus', 'code' => 'CY', 'flag' => '🇨🇾', 'phone_code' => '+357', 'phone_template' => '## ######', 'timezone' => 'Asia/Nicosia', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'flag' => '🇨🇿', 'phone_code' => '+420', 'phone_template' => '### ### ###', 'timezone' => 'Europe/Prague', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // D
            ['name' => 'Denmark', 'code' => 'DK', 'flag' => '🇩🇰', 'phone_code' => '+45', 'phone_template' => '## ## ## ##', 'timezone' => 'Europe/Copenhagen', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Djibouti', 'code' => 'DJ', 'flag' => '🇩🇯', 'phone_code' => '+253', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Djibouti', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Dominica', 'code' => 'DM', 'flag' => '🇩🇲', 'phone_code' => '+1767', 'phone_template' => '###-####', 'timezone' => 'America/Dominica', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'flag' => '🇩🇴', 'phone_code' => '+1809', 'phone_template' => '###-####', 'timezone' => 'America/Santo_Domingo', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],

            // E
            ['name' => 'Ecuador', 'code' => 'EC', 'flag' => '🇪🇨', 'phone_code' => '+593', 'phone_template' => '##-###-####', 'timezone' => 'America/Guayaquil', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Egypt', 'code' => 'EG', 'flag' => '🇪🇬', 'phone_code' => '+20', 'phone_template' => '### ### ####', 'timezone' => 'Africa/Cairo', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'El Salvador', 'code' => 'SV', 'flag' => '🇸🇻', 'phone_code' => '+503', 'phone_template' => '#### ####', 'timezone' => 'America/El_Salvador', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'flag' => '🇬🇶', 'phone_code' => '+240', 'phone_template' => '## ### ####', 'timezone' => 'Africa/Malabo', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Eritrea', 'code' => 'ER', 'flag' => '🇪🇷', 'phone_code' => '+291', 'phone_template' => '# ### ###', 'timezone' => 'Africa/Asmara', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Estonia', 'code' => 'EE', 'flag' => '🇪🇪', 'phone_code' => '+372', 'phone_template' => '#### ####', 'timezone' => 'Europe/Tallinn', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Eswatini', 'code' => 'SZ', 'flag' => '🇸🇿', 'phone_code' => '+268', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Mbabane', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Ethiopia', 'code' => 'ET', 'flag' => '🇪🇹', 'phone_code' => '+251', 'phone_template' => '## ### ####', 'timezone' => 'Africa/Addis_Ababa', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // F
            ['name' => 'Fiji', 'code' => 'FJ', 'flag' => '🇫🇯', 'phone_code' => '+679', 'phone_template' => '### ####', 'timezone' => 'Pacific/Fiji', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Finland', 'code' => 'FI', 'flag' => '🇫🇮', 'phone_code' => '+358', 'phone_template' => '## ### ####', 'timezone' => 'Europe/Helsinki', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'France', 'code' => 'FR', 'flag' => '🇫🇷', 'phone_code' => '+33', 'phone_template' => '## ## ## ## ##', 'timezone' => 'Europe/Paris', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // G
            ['name' => 'Gabon', 'code' => 'GA', 'flag' => '🇬🇦', 'phone_code' => '+241', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Libreville', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Gambia', 'code' => 'GM', 'flag' => '🇬🇲', 'phone_code' => '+220', 'phone_template' => '### ####', 'timezone' => 'Africa/Banjul', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Georgia', 'code' => 'GE', 'flag' => '🇬🇪', 'phone_code' => '+995', 'phone_template' => '### ### ###', 'timezone' => 'Asia/Tbilisi', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Germany', 'code' => 'DE', 'flag' => '🇩🇪', 'phone_code' => '+49', 'phone_template' => '### ### ####', 'timezone' => 'Europe/Berlin', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Ghana', 'code' => 'GH', 'flag' => '🇬🇭', 'phone_code' => '+233', 'phone_template' => '### ### ###', 'timezone' => 'Africa/Accra', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Greece', 'code' => 'GR', 'flag' => '🇬🇷', 'phone_code' => '+30', 'phone_template' => '### ### ####', 'timezone' => 'Europe/Athens', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Grenada', 'code' => 'GD', 'flag' => '🇬🇩', 'phone_code' => '+1473', 'phone_template' => '###-####', 'timezone' => 'America/Grenada', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Guatemala', 'code' => 'GT', 'flag' => '🇬🇹', 'phone_code' => '+502', 'phone_template' => '#### ####', 'timezone' => 'America/Guatemala', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Guinea', 'code' => 'GN', 'flag' => '🇬🇳', 'phone_code' => '+224', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Conakry', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'flag' => '🇬🇼', 'phone_code' => '+245', 'phone_template' => '### ####', 'timezone' => 'Africa/Bissau', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Guyana', 'code' => 'GY', 'flag' => '🇬🇾', 'phone_code' => '+592', 'phone_template' => '### ####', 'timezone' => 'America/Guyana', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // H
            ['name' => 'Haiti', 'code' => 'HT', 'flag' => '🇭🇹', 'phone_code' => '+509', 'phone_template' => '## ## ####', 'timezone' => 'America/Port-au-Prince', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Honduras', 'code' => 'HN', 'flag' => '🇭🇳', 'phone_code' => '+504', 'phone_template' => '#### ####', 'timezone' => 'America/Tegucigalpa', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Hungary', 'code' => 'HU', 'flag' => '🇭🇺', 'phone_code' => '+36', 'phone_template' => '### ### ###', 'timezone' => 'Europe/Budapest', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // I
            ['name' => 'Iceland', 'code' => 'IS', 'flag' => '🇮🇸', 'phone_code' => '+354', 'phone_template' => '### ####', 'timezone' => 'Atlantic/Reykjavik', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'India', 'code' => 'IN', 'flag' => '🇮🇳', 'phone_code' => '+91', 'phone_template' => '##### #####', 'timezone' => 'Asia/Kolkata', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Indonesia', 'code' => 'ID', 'flag' => '🇮🇩', 'phone_code' => '+62', 'phone_template' => '###-###-####', 'timezone' => 'Asia/Jakarta', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Iran', 'code' => 'IR', 'flag' => '🇮🇷', 'phone_code' => '+98', 'phone_template' => '### ### ####', 'timezone' => 'Asia/Tehran', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Iraq', 'code' => 'IQ', 'flag' => '🇮🇶', 'phone_code' => '+964', 'phone_template' => '### ### ####', 'timezone' => 'Asia/Baghdad', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Ireland', 'code' => 'IE', 'flag' => '🇮🇪', 'phone_code' => '+353', 'phone_template' => '## ### ####', 'timezone' => 'Europe/Dublin', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Israel', 'code' => 'IL', 'flag' => '🇮🇱', 'phone_code' => '+972', 'phone_template' => '##-###-####', 'timezone' => 'Asia/Jerusalem', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Italy', 'code' => 'IT', 'flag' => '🇮🇹', 'phone_code' => '+39', 'phone_template' => '### ### ####', 'timezone' => 'Europe/Rome', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Ivory Coast', 'code' => 'CI', 'flag' => '🇨🇮', 'phone_code' => '+225', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Abidjan', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // J
            ['name' => 'Jamaica', 'code' => 'JM', 'flag' => '🇯🇲', 'phone_code' => '+1876', 'phone_template' => '###-####', 'timezone' => 'America/Jamaica', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Japan', 'code' => 'JP', 'flag' => '🇯🇵', 'phone_code' => '+81', 'phone_template' => '###-####-####', 'timezone' => 'Asia/Tokyo', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Jordan', 'code' => 'JO', 'flag' => '🇯🇴', 'phone_code' => '+962', 'phone_template' => '# #### ####', 'timezone' => 'Asia/Amman', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // K
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'flag' => '🇰🇿', 'phone_code' => '+7', 'phone_template' => '### ###-##-##', 'timezone' => 'Asia/Almaty', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Kenya', 'code' => 'KE', 'flag' => '🇰🇪', 'phone_code' => '+254', 'phone_template' => '### ### ###', 'timezone' => 'Africa/Nairobi', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Kiribati', 'code' => 'KI', 'flag' => '🇰🇮', 'phone_code' => '+686', 'phone_template' => '## ###', 'timezone' => 'Pacific/Tarawa', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'North Korea', 'code' => 'KP', 'flag' => '🇰🇵', 'phone_code' => '+850', 'phone_template' => '### ### ####', 'timezone' => 'Asia/Pyongyang', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'South Korea', 'code' => 'KR', 'flag' => '🇰🇷', 'phone_code' => '+82', 'phone_template' => '###-####-####', 'timezone' => 'Asia/Seoul', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Kuwait', 'code' => 'KW', 'flag' => '🇰🇼', 'phone_code' => '+965', 'phone_template' => '#### ####', 'timezone' => 'Asia/Kuwait', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'flag' => '🇰🇬', 'phone_code' => '+996', 'phone_template' => '### ### ###', 'timezone' => 'Asia/Bishkek', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // L
            ['name' => 'Laos', 'code' => 'LA', 'flag' => '🇱🇦', 'phone_code' => '+856', 'phone_template' => '## ### ###', 'timezone' => 'Asia/Vientiane', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Latvia', 'code' => 'LV', 'flag' => '🇱🇻', 'phone_code' => '+371', 'phone_template' => '## ### ###', 'timezone' => 'Europe/Riga', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Lebanon', 'code' => 'LB', 'flag' => '🇱🇧', 'phone_code' => '+961', 'phone_template' => '## ### ###', 'timezone' => 'Asia/Beirut', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Lesotho', 'code' => 'LS', 'flag' => '🇱🇸', 'phone_code' => '+266', 'phone_template' => '## ### ###', 'timezone' => 'Africa/Maseru', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Liberia', 'code' => 'LR', 'flag' => '🇱🇷', 'phone_code' => '+231', 'phone_template' => '## ### ###', 'timezone' => 'Africa/Monrovia', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Libya', 'code' => 'LY', 'flag' => '🇱🇾', 'phone_code' => '+218', 'phone_template' => '##-#######', 'timezone' => 'Africa/Tripoli', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'flag' => '🇱🇮', 'phone_code' => '+423', 'phone_template' => '### ####', 'timezone' => 'Europe/Vaduz', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Lithuania', 'code' => 'LT', 'flag' => '🇱🇹', 'phone_code' => '+370', 'phone_template' => '### ## ###', 'timezone' => 'Europe/Vilnius', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Luxembourg', 'code' => 'LU', 'flag' => '🇱🇺', 'phone_code' => '+352', 'phone_template' => '### ### ###', 'timezone' => 'Europe/Luxembourg', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // M
            ['name' => 'Madagascar', 'code' => 'MG', 'flag' => '🇲🇬', 'phone_code' => '+261', 'phone_template' => '## ## ### ##', 'timezone' => 'Indian/Antananarivo', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Malawi', 'code' => 'MW', 'flag' => '🇲🇼', 'phone_code' => '+265', 'phone_template' => '## ### ####', 'timezone' => 'Africa/Blantyre', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Malaysia', 'code' => 'MY', 'flag' => '🇲🇾', 'phone_code' => '+60', 'phone_template' => '##-### ####', 'timezone' => 'Asia/Kuala_Lumpur', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Maldives', 'code' => 'MV', 'flag' => '🇲🇻', 'phone_code' => '+960', 'phone_template' => '###-####', 'timezone' => 'Indian/Maldives', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Mali', 'code' => 'ML', 'flag' => '🇲🇱', 'phone_code' => '+223', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Bamako', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Malta', 'code' => 'MT', 'flag' => '🇲🇹', 'phone_code' => '+356', 'phone_template' => '#### ####', 'timezone' => 'Europe/Malta', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'flag' => '🇲🇭', 'phone_code' => '+692', 'phone_template' => '###-####', 'timezone' => 'Pacific/Majuro', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Mauritania', 'code' => 'MR', 'flag' => '🇲🇷', 'phone_code' => '+222', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Nouakchott', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Mauritius', 'code' => 'MU', 'flag' => '🇲🇺', 'phone_code' => '+230', 'phone_template' => '#### ####', 'timezone' => 'Indian/Mauritius', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Mexico', 'code' => 'MX', 'flag' => '🇲🇽', 'phone_code' => '+52', 'phone_template' => '### ### ####', 'timezone' => 'America/Mexico_City', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Micronesia', 'code' => 'FM', 'flag' => '🇫🇲', 'phone_code' => '+691', 'phone_template' => '###-####', 'timezone' => 'Pacific/Chuuk', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Moldova', 'code' => 'MD', 'flag' => '🇲🇩', 'phone_code' => '+373', 'phone_template' => '## ### ###', 'timezone' => 'Europe/Chisinau', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Monaco', 'code' => 'MC', 'flag' => '🇲🇨', 'phone_code' => '+377', 'phone_template' => '## ## ## ##', 'timezone' => 'Europe/Monaco', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Mongolia', 'code' => 'MN', 'flag' => '🇲🇳', 'phone_code' => '+976', 'phone_template' => '#### ####', 'timezone' => 'Asia/Ulaanbaatar', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Montenegro', 'code' => 'ME', 'flag' => '🇲🇪', 'phone_code' => '+382', 'phone_template' => '## ### ###', 'timezone' => 'Europe/Podgorica', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Morocco', 'code' => 'MA', 'flag' => '🇲🇦', 'phone_code' => '+212', 'phone_template' => '###-###-###', 'timezone' => 'Africa/Casablanca', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Mozambique', 'code' => 'MZ', 'flag' => '🇲🇿', 'phone_code' => '+258', 'phone_template' => '## ### ####', 'timezone' => 'Africa/Maputo', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Myanmar', 'code' => 'MM', 'flag' => '🇲🇲', 'phone_code' => '+95', 'phone_template' => '###-###-####', 'timezone' => 'Asia/Yangon', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // N
            ['name' => 'Namibia', 'code' => 'NA', 'flag' => '🇳🇦', 'phone_code' => '+264', 'phone_template' => '## ### ####', 'timezone' => 'Africa/Windhoek', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Nauru', 'code' => 'NR', 'flag' => '🇳🇷', 'phone_code' => '+674', 'phone_template' => '### ####', 'timezone' => 'Pacific/Nauru', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Nepal', 'code' => 'NP', 'flag' => '🇳🇵', 'phone_code' => '+977', 'phone_template' => '###-#######', 'timezone' => 'Asia/Kathmandu', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Netherlands', 'code' => 'NL', 'flag' => '🇳🇱', 'phone_code' => '+31', 'phone_template' => '## ### ####', 'timezone' => 'Europe/Amsterdam', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'New Zealand', 'code' => 'NZ', 'flag' => '🇳🇿', 'phone_code' => '+64', 'phone_template' => '##-### ####', 'timezone' => 'Pacific/Auckland', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Nicaragua', 'code' => 'NI', 'flag' => '🇳🇮', 'phone_code' => '+505', 'phone_template' => '#### ####', 'timezone' => 'America/Managua', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Niger', 'code' => 'NE', 'flag' => '🇳🇪', 'phone_code' => '+227', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Niamey', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Nigeria', 'code' => 'NG', 'flag' => '🇳🇬', 'phone_code' => '+234', 'phone_template' => '### ### ####', 'timezone' => 'Africa/Lagos', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'North Macedonia', 'code' => 'MK', 'flag' => '🇲🇰', 'phone_code' => '+389', 'phone_template' => '## ### ###', 'timezone' => 'Europe/Skopje', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Norway', 'code' => 'NO', 'flag' => '🇳🇴', 'phone_code' => '+47', 'phone_template' => '### ## ###', 'timezone' => 'Europe/Oslo', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // O
            ['name' => 'Oman', 'code' => 'OM', 'flag' => '🇴🇲', 'phone_code' => '+968', 'phone_template' => '#### ####', 'timezone' => 'Asia/Muscat', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // P
            ['name' => 'Pakistan', 'code' => 'PK', 'flag' => '🇵🇰', 'phone_code' => '+92', 'phone_template' => '### ### ####', 'timezone' => 'Asia/Karachi', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Palau', 'code' => 'PW', 'flag' => '🇵🇼', 'phone_code' => '+680', 'phone_template' => '###-####', 'timezone' => 'Pacific/Palau', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Palestine', 'code' => 'PS', 'flag' => '🇵🇸', 'phone_code' => '+970', 'phone_template' => '### ### ###', 'timezone' => 'Asia/Gaza', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Panama', 'code' => 'PA', 'flag' => '🇵🇦', 'phone_code' => '+507', 'phone_template' => '#### ####', 'timezone' => 'America/Panama', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'flag' => '🇵🇬', 'phone_code' => '+675', 'phone_template' => '### ####', 'timezone' => 'Pacific/Port_Moresby', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Paraguay', 'code' => 'PY', 'flag' => '🇵🇾', 'phone_code' => '+595', 'phone_template' => '### ### ###', 'timezone' => 'America/Asuncion', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Peru', 'code' => 'PE', 'flag' => '🇵🇪', 'phone_code' => '+51', 'phone_template' => '### ### ###', 'timezone' => 'America/Lima', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Philippines', 'code' => 'PH', 'flag' => '🇵🇭', 'phone_code' => '+63', 'phone_template' => '### ### ####', 'timezone' => 'Asia/Manila', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Poland', 'code' => 'PL', 'flag' => '🇵🇱', 'phone_code' => '+48', 'phone_template' => '### ### ###', 'timezone' => 'Europe/Warsaw', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Portugal', 'code' => 'PT', 'flag' => '🇵🇹', 'phone_code' => '+351', 'phone_template' => '### ### ###', 'timezone' => 'Europe/Lisbon', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // Q
            ['name' => 'Qatar', 'code' => 'QA', 'flag' => '🇶🇦', 'phone_code' => '+974', 'phone_template' => '#### ####', 'timezone' => 'Asia/Qatar', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // R
            ['name' => 'Romania', 'code' => 'RO', 'flag' => '🇷🇴', 'phone_code' => '+40', 'phone_template' => '### ### ###', 'timezone' => 'Europe/Bucharest', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Russia', 'code' => 'RU', 'flag' => '🇷🇺', 'phone_code' => '+7', 'phone_template' => '### ###-##-##', 'timezone' => 'Europe/Moscow', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Rwanda', 'code' => 'RW', 'flag' => '🇷🇼', 'phone_code' => '+250', 'phone_template' => '### ### ###', 'timezone' => 'Africa/Kigali', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // S
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'flag' => '🇰🇳', 'phone_code' => '+1869', 'phone_template' => '###-####', 'timezone' => 'America/St_Kitts', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'flag' => '🇱🇨', 'phone_code' => '+1758', 'phone_template' => '###-####', 'timezone' => 'America/St_Lucia', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'flag' => '🇻🇨', 'phone_code' => '+1784', 'phone_template' => '###-####', 'timezone' => 'America/St_Vincent', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Samoa', 'code' => 'WS', 'flag' => '🇼🇸', 'phone_code' => '+685', 'phone_template' => '## ####', 'timezone' => 'Pacific/Apia', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'San Marino', 'code' => 'SM', 'flag' => '🇸🇲', 'phone_code' => '+378', 'phone_template' => '#### ######', 'timezone' => 'Europe/San_Marino', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'flag' => '🇸🇹', 'phone_code' => '+239', 'phone_template' => '## #####', 'timezone' => 'Africa/Sao_Tome', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'flag' => '🇸🇦', 'phone_code' => '+966', 'phone_template' => '## ### ####', 'timezone' => 'Asia/Riyadh', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Senegal', 'code' => 'SN', 'flag' => '🇸🇳', 'phone_code' => '+221', 'phone_template' => '## ### ## ##', 'timezone' => 'Africa/Dakar', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Serbia', 'code' => 'RS', 'flag' => '🇷🇸', 'phone_code' => '+381', 'phone_template' => '## ### ####', 'timezone' => 'Europe/Belgrade', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Seychelles', 'code' => 'SC', 'flag' => '🇸🇨', 'phone_code' => '+248', 'phone_template' => '# ### ###', 'timezone' => 'Indian/Mahe', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'flag' => '🇸🇱', 'phone_code' => '+232', 'phone_template' => '## ######', 'timezone' => 'Africa/Freetown', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Singapore', 'code' => 'SG', 'flag' => '🇸🇬', 'phone_code' => '+65', 'phone_template' => '#### ####', 'timezone' => 'Asia/Singapore', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Slovakia', 'code' => 'SK', 'flag' => '🇸🇰', 'phone_code' => '+421', 'phone_template' => '### ### ###', 'timezone' => 'Europe/Bratislava', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Slovenia', 'code' => 'SI', 'flag' => '🇸🇮', 'phone_code' => '+386', 'phone_template' => '## ### ###', 'timezone' => 'Europe/Ljubljana', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'flag' => '🇸🇧', 'phone_code' => '+677', 'phone_template' => '## ###', 'timezone' => 'Pacific/Guadalcanal', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Somalia', 'code' => 'SO', 'flag' => '🇸🇴', 'phone_code' => '+252', 'phone_template' => '## ### ###', 'timezone' => 'Africa/Mogadishu', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'South Africa', 'code' => 'ZA', 'flag' => '🇿🇦', 'phone_code' => '+27', 'phone_template' => '## ### ####', 'timezone' => 'Africa/Johannesburg', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'South Sudan', 'code' => 'SS', 'flag' => '🇸🇸', 'phone_code' => '+211', 'phone_template' => '### ### ###', 'timezone' => 'Africa/Juba', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Spain', 'code' => 'ES', 'flag' => '🇪🇸', 'phone_code' => '+34', 'phone_template' => '### ### ###', 'timezone' => 'Europe/Madrid', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'flag' => '🇱🇰', 'phone_code' => '+94', 'phone_template' => '## ### ####', 'timezone' => 'Asia/Colombo', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Sudan', 'code' => 'SD', 'flag' => '🇸🇩', 'phone_code' => '+249', 'phone_template' => '### ### ###', 'timezone' => 'Africa/Khartoum', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Suriname', 'code' => 'SR', 'flag' => '🇸🇷', 'phone_code' => '+597', 'phone_template' => '###-####', 'timezone' => 'America/Paramaribo', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Sweden', 'code' => 'SE', 'flag' => '🇸🇪', 'phone_code' => '+46', 'phone_template' => '## ### ## ##', 'timezone' => 'Europe/Stockholm', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Switzerland', 'code' => 'CH', 'flag' => '🇨🇭', 'phone_code' => '+41', 'phone_template' => '## ### ## ##', 'timezone' => 'Europe/Zurich', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Syria', 'code' => 'SY', 'flag' => '🇸🇾', 'phone_code' => '+963', 'phone_template' => '### ### ###', 'timezone' => 'Asia/Damascus', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // T
            ['name' => 'Tajikistan', 'code' => 'TJ', 'flag' => '🇹🇯', 'phone_code' => '+992', 'phone_template' => '### ### ###', 'timezone' => 'Asia/Dushanbe', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Tanzania', 'code' => 'TZ', 'flag' => '🇹🇿', 'phone_code' => '+255', 'phone_template' => '### ### ###', 'timezone' => 'Africa/Dar_es_Salaam', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Thailand', 'code' => 'TH', 'flag' => '🇹🇭', 'phone_code' => '+66', 'phone_template' => '##-###-####', 'timezone' => 'Asia/Bangkok', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'flag' => '🇹🇱', 'phone_code' => '+670', 'phone_template' => '### ####', 'timezone' => 'Asia/Dili', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Togo', 'code' => 'TG', 'flag' => '🇹🇬', 'phone_code' => '+228', 'phone_template' => '## ## ## ##', 'timezone' => 'Africa/Lome', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Tonga', 'code' => 'TO', 'flag' => '🇹🇴', 'phone_code' => '+676', 'phone_template' => '## ###', 'timezone' => 'Pacific/Tongatapu', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'flag' => '🇹🇹', 'phone_code' => '+1868', 'phone_template' => '###-####', 'timezone' => 'America/Port_of_Spain', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Tunisia', 'code' => 'TN', 'flag' => '🇹🇳', 'phone_code' => '+216', 'phone_template' => '## ### ###', 'timezone' => 'Africa/Tunis', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Turkey', 'code' => 'TR', 'flag' => '🇹🇷', 'phone_code' => '+90', 'phone_template' => '### ### ## ##', 'timezone' => 'Europe/Istanbul', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'flag' => '🇹🇲', 'phone_code' => '+993', 'phone_template' => '## ######', 'timezone' => 'Asia/Ashgabat', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Tuvalu', 'code' => 'TV', 'flag' => '🇹🇻', 'phone_code' => '+688', 'phone_template' => '## ###', 'timezone' => 'Pacific/Funafuti', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // U
            ['name' => 'Uganda', 'code' => 'UG', 'flag' => '🇺🇬', 'phone_code' => '+256', 'phone_template' => '### ### ###', 'timezone' => 'Africa/Kampala', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Ukraine', 'code' => 'UA', 'flag' => '🇺🇦', 'phone_code' => '+380', 'phone_template' => '## ### ## ##', 'timezone' => 'Europe/Kiev', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'flag' => '🇦🇪', 'phone_code' => '+971', 'phone_template' => '## ### ####', 'timezone' => 'Asia/Dubai', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'United Kingdom', 'code' => 'GB', 'flag' => '🇬🇧', 'phone_code' => '+44', 'phone_template' => '#### ### ####', 'timezone' => 'Europe/London', 'time_format' => '24', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'celsius']],
            ['name' => 'United States', 'code' => 'US', 'flag' => '🇺🇸', 'phone_code' => '+1', 'phone_template' => '(###) ###-####', 'timezone' => 'America/New_York', 'time_format' => '12', 'unit_measurements' => ['length' => 'ft', 'weight' => 'lbs', 'temperature' => 'fahrenheit']],
            ['name' => 'Uruguay', 'code' => 'UY', 'flag' => '🇺🇾', 'phone_code' => '+598', 'phone_template' => '#### ####', 'timezone' => 'America/Montevideo', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'flag' => '🇺🇿', 'phone_code' => '+998', 'phone_template' => '## ### ## ##', 'timezone' => 'Asia/Tashkent', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // V
            ['name' => 'Vanuatu', 'code' => 'VU', 'flag' => '🇻🇺', 'phone_code' => '+678', 'phone_template' => '## ###', 'timezone' => 'Pacific/Efate', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Vatican City', 'code' => 'VA', 'flag' => '🇻🇦', 'phone_code' => '+379', 'phone_template' => '## ## ## ##', 'timezone' => 'Europe/Vatican', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Venezuela', 'code' => 'VE', 'flag' => '🇻🇪', 'phone_code' => '+58', 'phone_template' => '###-#######', 'timezone' => 'America/Caracas', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Vietnam', 'code' => 'VN', 'flag' => '🇻🇳', 'phone_code' => '+84', 'phone_template' => '### ### ####', 'timezone' => 'Asia/Ho_Chi_Minh', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // Y
            ['name' => 'Yemen', 'code' => 'YE', 'flag' => '🇾🇪', 'phone_code' => '+967', 'phone_template' => '### ### ###', 'timezone' => 'Asia/Aden', 'time_format' => '12', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],

            // Z
            ['name' => 'Zambia', 'code' => 'ZM', 'flag' => '🇿🇲', 'phone_code' => '+260', 'phone_template' => '## ### ####', 'timezone' => 'Africa/Lusaka', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'flag' => '🇿🇼', 'phone_code' => '+263', 'phone_template' => '## ### ####', 'timezone' => 'Africa/Harare', 'time_format' => '24', 'unit_measurements' => ['length' => 'cm', 'weight' => 'kg', 'temperature' => 'celsius']]
        ];

        foreach ($countries as $country) {
            // Convert unit_measurements array to JSON string
            $country['unit_measurements'] = json_encode($country['unit_measurements']);
            Country::create($country);
        }
    }
}